### ISSUE TITLE
Timeout during AXFR

### ISSUE THREAD

**Issue by timmc** [mschwager/fierce#23]
I frequently receive a timeout during the zone transfer step that kills fierce. The program hangs for several minutes after printing the SOA, then crashes with the following:

```
Traceback (most recent call last):
  File "./fierce.py", line 409, in <module>
    main()
  File "./fierce.py", line 406, in main
    fierce(**vars(args))
  File "./fierce.py", line 266, in fierce
    zone = zone_transfer(master_address, domain)
  File "./fierce.py", line 138, in zone_transfer
    return dns.zone.from_xfr(dns.query.xfr(address, domain))
  File "/usr/lib/python3/dist-packages/dns/zone.py", line 979, in from_xfr
    for r in xfr:
  File "/usr/lib/python3/dist-packages/dns/query.py", line 412, in xfr
    _net_write(s, tcpmsg, expiration)
  File "/usr/lib/python3/dist-packages/dns/query.py", line 260, in _net_write
    current += sock.send(data[current:])
TimeoutError: [Errno 110] Connection timed out
```

This is on current master (9334f0f6f5cae1a804cda557bc69ac5f84ef822a) but was present in 1.1.5 as well.

**Comment by mschwager** [comment]
Thanks again! I will try to release a new version shortly with all these bug fixes :)
