### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by PatrikFehrenbach** [mschwager/fierce#6]
File "/usr/local/bin/fierce", line 9, in <module>
    load_entry_point('fierce==1.0', 'console_scripts', 'fierce')()
  File "/usr/local/lib/python3.5/site-packages/fierce-1.0-py3.5.egg/fierce.py", line 235, in main
  File "/usr/local/lib/python3.5/site-packages/fierce-1.0-py3.5.egg/fierce.py", line 137, in fierce
TypeError: 'NoneType' object is not subscriptable

**Comment by mschwager** [comment]
Could you provide the command you ran to get that exception?

**Comment by hollow1** [comment]
Traceback (most recent call last):
  File "./fierce.py", line 238, in <module>
    main()
  File "./fierce.py", line 235, in main
    fierce(**vars(args))
  File "./fierce.py", line 167, in fierce
    ip = ipaddress.IPv4Address(record[0].address)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/dns/resolver.py", line 192, in __getitem__
    return self.rrset[i]
TypeError: 'NoneType' object is not subscriptable

**Comment by mschwager** [comment]
Again, if you could provide the command you ran to  get this exception it would be helpful.

Also, this appears to be a separate issue, despite the exception being the same.

**Comment by yangyangwithgnu** [comment]
@mschwager  same to me. the command info as following:

~/downloads/fierce # python3 fierce.py --domain baidu.com --subdomains accounts admin ads
NS: ns7.baidu.com. dns.baidu.com. ns2.baidu.com. ns4.baidu.com. ns3.baidu.com.
SOA: dns.baidu.com. (202.108.22.220)
Zone: failure
Wildcard: success
Found: accounts.baidu.com. (10.11.252.74)
Nearby:
Traceback (most recent call last):
  File "fierce.py", line 301, in <module>
    main()
  File "fierce.py", line 298, in main
    fierce(**vars(args))
  File "fierce.py", line 246, in fierce
    find_nearby(resolver, ips, filter_func=filter_func)
  File "fierce.py", line 162, in find_nearby
    pprint.pprint({k: v[0].to_text() for k, v in reversed_ips.items()})
  File "fierce.py", line 162, in <dictcomp>
    pprint.pprint({k: v[0].to_text() for k, v in reversed_ips.items()})
  File "/usr/lib/python3.4/site-packages/dns/resolver.py", line 192, in __getitem__
    return self.rrset[i]
TypeError: 'NoneType' object is not subscriptable

**Comment by mschwager** [comment]
Unfortunately I wasn't able to reproduce with the same command. However, after some digging I think I found the issue. I believe https://github.com/mschwager/fierce/commit/8a5156834c87f6262fb87bc045191ab1ee7ffc8a should fix it. Can you confirm?

**Comment by dxa4481** [comment]
@mschwager I am experiencing this error when attempting to enumerate sub-subdomains. For example 
```
--domain "anything.google.com" 
```

Will throw the error.
